name: Cypress Tests with Page Objects

on:
  push:
    branches: [ CI ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install dependencies
    - run: npm install

    # Run Cypress tests
    - name: Run Cypress Tests
      run: npx cypress run

    # Publish Cypress Report
    - name: Publish Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cypress/reports
